### ISSUE TITLE
typo, mini-minor

### ISSUE THREAD

**Issue by josok64** [devrt/docker-firehol-update-ipsets#1]
$ docker volume create firehol-update-upsets
$ docker run --name firehol-update-ipsets -it -d --restart=always --cap-add=NET_ADMIN --net=host -v firehol-update-ipsets:/etc/firehol/ipsets devrt/firehol-update-ipsets
-----------------------------first line, should be ....ipsets, not ......upsets.
Since docker creates the volume if not existing, there is no impact on the functionality.
And eh Thanks, works like a charm!

**Comment by yosuke** [comment]
Thank you for letting me know (and sorry for taking so long time to get notice about this report).

Fixed.
